# Introduction

The goal of this notebook is to combine and integrate data from multiple sources using join and merge operations in pandas.

The dataset `empleadosTecnologiaAlpesMod3y4.xlsx` contains several sheets. The main sheet, “employeesTechnologyAlps,” stores information about employees, including the numerical codes for the department (`ID Departamento`) and the position (`Rol ID`). The “Departamentos” and “Roles” sheets contain the corresponding descriptive labels. 

The “Viajes por Empleado” sheet contains the pre-organized list of employee travel frequency, so the join function will be used to append this information to the final dataset.

This approach provides hands-on experience in combining datasets, handling mismatched keys, and understanding how different types of joins affect the final result.

# Import libraries

In [2]:
import pandas as pd

# merge exercise

In [5]:
employee_data=pd.read_excel('empleadosTecnologiaAlpesMod3y4.xlsx', sheet_name='empleadosTecnologíaAlpes')
employee_data.head(5)

,Edad,Retirado,TarifaSalarial,ID Departamento,DistanciaDesdeCasa,Educacion,CampoEducacion,EmpleadosACargo,NumeroEmpleado,NivelSatisfaccion,...,HorasEstandar,PlanSalarioComplementario,TotalAnniosTrabajados,FormacionUltimoAnnio,BalanceTrabajoVida,FechaIngresoEmpresa,AnniosEnEmpresa,AnniosRolActual,AnniosDesdeUltimaPromocion,AnniosActualDirector
0,41,Si,1102,3,1,2,Ciencias de la vida,1.0,1,2,...,80,0,8,0,1,2015-07-26,6,4,0,5
1,49,No,279,1,8,1,Ciencias de la vida,1.0,2,3,...,80,1,10,3,3,2011-02-15,10,7,1,7
2,37,Si,1373,1,2,2,Otro,1.0,4,4,...,80,0,7,3,3,2021-06-02,0,0,0,0
3,33,No,1392,1,3,4,Ciencias de la vida,1.0,5,4,...,80,0,8,3,3,2013-09-26,8,7,3,0
4,27,No,591,1,2,1,Medicina,1.0,7,1,...,80,1,6,3,3,2019-03-02,2,2,2,2

In [6]:
employee_data.dtypes

Edad                                               int64
Retirado                                          object
TarifaSalarial                                     int64
ID Departamento                                    int64
DistanciaDesdeCasa                                 int64
Educacion                                          int64
CampoEducacion                                    object
EmpleadosACargo                                  float64
NumeroEmpleado                                     int64
NivelSatisfaccion                                  int64
Genero                                            object
SalarioPorHora                                     int64
NivelInvolucramiento                               int64
NivelResponsabilidad                               int64
Rol ID                                             int64
SatisfaccionTrabajo                                int64
EstadoCivil                                       object
SalarioMensual                                     int64
TarifaMensual                                      int64
NumEmpresasDondeTrabaja                            int64
MasDe18Horas                                      object
HorasExtra                                        object
PorcentajeIncrementoSalarioUltimoAnnio             int64
NivelRendimiento                                   int64
SatisfaccionEmpresa                                int64
HorasEstandar                                      int64
PlanSalarioComplementario                          int64
TotalAnniosTrabajados                              int64
FormacionUltimoAnnio                               int64
BalanceTrabajoVida                                 int64
FechaIngresoEmpresa                       datetime64[ns]
AnniosEnEmpresa                                    int64
AnniosRolActual                                    int64
AnniosDesdeUltimaPromocion                         int64
AnniosActualDirector                               int64
dtype: object

In [7]:
employee_data = employee_data[['Edad', 'Retirado', 'ID Departamento', 'Rol ID']]
employee_data.head(5)

   Edad Retirado  ID Departamento  Rol ID
0    41       Si                3       5
1    49       No                1       1
2    37       Si                1       9
3    33       No                1       1
4    27       No                1       9

The primary keys are 'ID Departamento' and 'Rol ID'

In [8]:
data_Roles=pd.read_excel('empleadosTecnologiaAlpesMod3y4.xlsx', sheet_name='Roles')
data_Roles.head(5)

   ID                          Rol
0   1  Cientifico de investigacion
1   2                     Director
2   3    Director de investigacion
3   4      Director de manufactura
4   5          Ejecutivo de ventas

In [9]:
data_Departments=pd.read_excel('empleadosTecnologiaAlpesMod3y4.xlsx', sheet_name='Departamentos')
data_Departments.head(5)

   ID                Departamento
0   1  Investigacion & Desarrollo
1   2              Talento Humano
2   3                      Ventas

In [11]:
data_final = employee_data.merge(
    data_Departments,
    left_on='ID Departamento',
    right_on='ID',
    how='left')
data_final.head()

   Edad Retirado  ID Departamento  Rol ID  ID                Departamento
0    41       Si                3       5   3                      Ventas
1    49       No                1       1   1  Investigacion & Desarrollo
2    37       Si                1       9   1  Investigacion & Desarrollo
3    33       No                1       1   1  Investigacion & Desarrollo
4    27       No                1       9   1  Investigacion & Desarrollo

In [12]:
data_final = data_final.merge(
    data_Roles,
    left_on='Rol ID',
    right_on='ID',
    how='left')
data_final.head()

,Edad,Retirado,ID Departamento,Rol ID,ID_x,Departamento,ID_y,Rol
0,41,Si,3,5,3,Ventas,5,Ejecutivo de ventas
1,49,No,1,1,1,Investigacion & Desarrollo,1,Cientifico de investigacion
2,37,Si,1,9,1,Investigacion & Desarrollo,9,Tecnico de laboratorio
3,33,No,1,1,1,Investigacion & Desarrollo,1,Cientifico de investigacion
4,27,No,1,9,1,Investigacion & Desarrollo,9,Tecnico de laboratorio

In [13]:
data_final = data_final.drop(columns=['ID_x', 'ID Departamento','ID_y','Rol ID'])
data_final.head()

   Edad Retirado                Departamento                          Rol
0    41       Si                      Ventas          Ejecutivo de ventas
1    49       No  Investigacion & Desarrollo  Cientifico de investigacion
2    37       Si  Investigacion & Desarrollo       Tecnico de laboratorio
3    33       No  Investigacion & Desarrollo  Cientifico de investigacion
4    27       No  Investigacion & Desarrollo       Tecnico de laboratorio

Let's explore the dataset

In [14]:
data_final['Departamento'].value_counts()

Departamento
Investigacion & Desarrollo    974
Ventas                        451
Talento Humano                 67
Name: count, dtype: int64

In [15]:
data_final['Rol'].value_counts()

Rol
Ejecutivo de ventas              329
Cientifico de investigacion      297
Tecnico de laboratorio           267
Director de manufactura          145
Representante atencion medica    131
Director                         102
Representante de ventas           87
Director de investigacion         80
Talento Humano                    54
Name: count, dtype: int64

In [21]:
data_final.groupby('Rol')['Departamento'].unique()

Rol
Cientifico de investigacion                           [Investigacion & Desarrollo]
Director                         [Ventas, Investigacion & Desarrollo, Talento H...
Director de investigacion                             [Investigacion & Desarrollo]
Director de manufactura                               [Investigacion & Desarrollo]
Ejecutivo de ventas                                                       [Ventas]
Representante atencion medica                         [Investigacion & Desarrollo]
Representante de ventas                                                   [Ventas]
Talento Humano                                                    [Talento Humano]
Tecnico de laboratorio                                [Investigacion & Desarrollo]
Name: Departamento, dtype: object

In [24]:
data_final.pivot_table(index='Rol', columns='Departamento', aggfunc='size', fill_value=0)

Departamento,Investigacion & Desarrollo,Talento Humano,Ventas
Rol,,,
Cientifico de investigacion,297,0,0
Director,54,13,35
Director de investigacion,80,0,0
Director de manufactura,145,0,0
Ejecutivo de ventas,0,0,329
Representante atencion medica,131,0,0
Representante de ventas,0,0,87
Talento Humano,0,54,0
Tecnico de laboratorio,267,0,0

# join exercise

In [25]:
data_Travel=pd.read_excel('empleadosTecnologiaAlpesMod3y4.xlsx', sheet_name='Viajes por Empleado')
data_Travel.head(5)

        ViajesDeNegocio
0     Viaja-Pocas-Veces
1  Viaja-Frecuentemente
2     Viaja-Pocas-Veces
3  Viaja-Frecuentemente
4     Viaja-Pocas-Veces

In [28]:
data_final = data_final.reset_index(drop=True)
data_Travel = data_Travel.reset_index(drop=True)

data_final = data_final.join(data_Travel)
data_final.head()

,Edad,Retirado,Departamento,Rol,ViajesDeNegocio
0,41,Si,Ventas,Ejecutivo de ventas,Viaja-Pocas-Veces
1,49,No,Investigacion & Desarrollo,Cientifico de investigacion,Viaja-Frecuentemente
2,37,Si,Investigacion & Desarrollo,Tecnico de laboratorio,Viaja-Pocas-Veces
3,33,No,Investigacion & Desarrollo,Cientifico de investigacion,Viaja-Frecuentemente
4,27,No,Investigacion & Desarrollo,Tecnico de laboratorio,Viaja-Pocas-Veces

In [29]:
data_final.pivot_table(index='Rol', columns='ViajesDeNegocio', aggfunc='size', fill_value=0)

ViajesDeNegocio,No-Viaja,Viaja-Frecuentemente,Viaja-Pocas-Veces
Rol,,,
Cientifico de investigacion,28,57,212
Director,12,13,77
Director de investigacion,6,12,62
Director de manufactura,13,29,103
Ejecutivo de ventas,40,59,230
Representante atencion medica,15,26,90
Representante de ventas,5,25,57
Talento Humano,4,11,39
Tecnico de laboratorio,28,52,187