# Exercise 1

The purpose of this workbook is to import data from different file types; in this case, we will use .csv, .xlsx, and .json files.

# 1. Import libraries

In [1]:
import pandas as pd
import os
import json

# csv file

In [8]:
data_csv = pd.read_csv('productos_por_fecha.csv', sep=';',encoding = 'latin-1')
data_csv.head()

,producto_id,fecha_envio_limite,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
0,PT66,19/09/2017 07:24,Tarjetas regalo,6,34,18,50,9,12
1,PB76,22/01/2018 11:30,Ropa de adultos,10,39,0,26,24,23
2,PJ55,09/12/2017 15:09,Mascotas,25,12,3,51,2,28
3,PO85,04/05/2018 04:15,Productos ecoamigables,33,25,25,19,26,28
4,PG31,17/09/2017 23:24,Salud,34,22,11,39,19,40

In [9]:
data_csv.shape

(1000, 9)

In [10]:
data_csv.dtypes

producto_id                      object
fecha_envio_limite               object
nombre_categoria_producto        object
longitud_nombre_producto          int64
longitud_descripcion_producto     int64
cantidad_fotos_producto           int64
longitud_cm_producto              int64
altura_cm_producto                int64
ancho_cm_producto                 int64
dtype: object

#### Best-selling categories

In [11]:
data_csv['nombre_categoria_producto'].value_counts()

nombre_categoria_producto
Ropa de adultos           70
Mascotas                  69
Juguetes                  65
Tarjetas regalo           60
Frutas y verduras         57
Tecnología                55
Celulares                 51
Bebés                     50
Libros                    49
Licor                     48
Deportes                  48
Ropa infantil             46
Ferretería                45
Muebles                   44
Lácteos                   44
Productos ecoamigables    43
Electrodomésticos         42
Dormitorio                41
Salud                     39
Carnicería                34
Name: count, dtype: int64

We need to change the data type of the ‘fecha_envio_limite’ variable to datetime

In [12]:
data_csv['fecha_envio_limite'] = pd.to_datetime(data_csv['fecha_envio_limite'].astype(str), dayfirst=True)
data_csv['fecha_envio_limite']

0     2017-09-19 07:24:00
1     2018-01-22 11:30:00
2     2017-12-09 15:09:00
3     2018-05-04 04:15:00
4     2017-09-17 23:24:00
              ...
995   2018-02-24 02:58:00
996   2018-02-10 22:42:00
997   2017-08-07 03:24:00
998   2017-12-19 00:54:00
999   2018-04-08 18:38:00
Name: fecha_envio_limite, Length: 1000, dtype: datetime64[ns]

### Days with the highest sales

In [13]:
data_csv['fecha_envio_limite'] = pd.to_datetime(data_csv['fecha_envio_limite'], dayfirst=True)
data_csv['day_month'] = data_csv['fecha_envio_limite'].dt.strftime('%d-%m')

shopping_per_day = data_csv['day_month'].value_counts()

print(shopping_per_day.head())

day_month
30-11    10
17-08     9
31-07     8
21-08     8
21-02     8
Name: count, dtype: int64

# xslx file

In [16]:
data_excel_1 = pd.read_excel('productos_por_fecha.xlsx', sheet_name='Datos 1')
data_excel_1.head()

,producto_id,fecha_envio_limite,nombre_categoria_producto,0,1,2,4,altura_cm_producto,ancho_cm_producto
0,PT66,19/09/2017 07:24,Tarjetas regalo,6,34,18,50,9,12
1,PB76,22/01/2018 11:30,Ropa de adultos,10,39,0,26,24,23
2,PJ55,09/12/2017 15:09,Mascotas,25,12,3,51,2,28
3,PO85,04/05/2018 04:15,Productos ecoamigables,33,25,25,19,26,28
4,PG31,17/09/2017 23:24,Salud,34,22,11,39,19,40

In [17]:
data_excel_2 = pd.read_excel('productos_por_fecha.xlsx', sheet_name='Datos 2')
data_excel_2.head()

,producto_id,fecha_envio_limite,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
0,PT66,19/09/2017 07:24,Tarjetas regalo,6,34,18,50,9,12
1,PB76,22/01/2018 11:30,Ropa de adultos,10,39,0,26,24,23
2,PJ55,09/12/2017 15:09,Mascotas,25,12,3,51,2,28
3,PO85,04/05/2018 04:15,Productos ecoamigables,33,25,25,19,26,28
4,PG31,17/09/2017 23:24,Salud,34,22,11,39,19,40

In this case, two datasets from the same Excel file were loaded; they were on different sheets. As you can see, some of the column names in “data_excel_1” are incorrectly spelled.

In [18]:
print(data_excel_1.shape)
print(data_excel_2.shape)

(100, 9)
(1000, 9)

In [19]:
print(data_excel_1.dtypes)

producto_id                  object
fecha_envio_limite           object
nombre_categoria_producto    object
0                             int64
1                             int64
2                             int64
4                             int64
altura_cm_producto            int64
ancho_cm_producto             int64
dtype: object

In [20]:
print(data_excel_2.dtypes)

producto_id                      object
fecha_envio_limite               object
nombre_categoria_producto        object
longitud_nombre_producto          int64
longitud_descripcion_producto     int64
cantidad_fotos_producto           int64
longitud_cm_producto              int64
altura_cm_producto                int64
ancho_cm_producto                 int64
dtype: object

We converted the format of the ‘fecha_envio_limite’ column to the datetime type, again

In [21]:
data_excel_1['fecha_envio_limite'] = pd.to_datetime(data_excel_1['fecha_envio_limite'], dayfirst=True)
data_excel_2['fecha_envio_limite'] = pd.to_datetime(data_excel_2['fecha_envio_limite'], dayfirst=True)

### Days with the highest sales

In [23]:
for i, df in enumerate([data_excel_1, data_excel_2], 1):
    days = pd.to_datetime(df['fecha_envio_limite'], dayfirst=True).dt.strftime('%d-%m').value_counts()
    print(f"Data {i} - Best day: {days.index[0]} ({days.iloc[0]} ventas)")
    print(days.head(), "\n")

Data 1 - Best day: 15-07 (3 ventas)
fecha_envio_limite
15-07    3
31-07    2
16-06    2
31-01    2
19-09    2
Name: count, dtype: int64

Data 2 - Best day: 30-11 (10 ventas)
fecha_envio_limite
30-11    10
17-08     9
31-07     8
21-08     8
21-02     8
Name: count, dtype: int64

### Best-selling categories

In [24]:
for i, df in enumerate([data_excel_1, data_excel_2], 1):
    category = df['nombre_categoria_producto'].value_counts()
    print(f"Data {i} - Top category: '{category.index[0]}' ({category.iloc[0]} times)")

Data 1 - Top category: 'Juguetes' (10 times)
Data 2 - Top category: 'Ropa de adultos' (70 times)

# json file

In [26]:
f = open('productos_por_fecha.json')

data_json = json.load(f)

show_data = {}
for i in data_json.keys():
    show_data[i] = dict(list(data_json[i].items()))

show_data

{'producto_id': {'8657': 'PT66',
  '5070': 'PB76',
  '2412': 'PJ55',
  '5147': 'PO85',
  '4667': 'PG31',
  '7274': 'PC48',
  '8710': 'PK81',
  '4529': 'PO23',
  '4039': 'PN99',
  '3042': 'PD94'},
 'fecha_envio_limite': {'8657': '19/09/2017 07:24',
  '5070': '22/01/2018 11:30',
  '2412': '09/12/2017 15:09',
  '5147': '04/05/2018 04:15',
  '4667': '17/09/2017 23:24',
  '7274': '22/11/2017 01:10',
  '8710': '23/02/2018 04:05',
  '4529': '14/03/2018 19:45',
  '4039': '05/03/2018 09:58',
  '3042': '22/04/2018 02:19'},
 'nombre_categoria_producto': {'8657': 'Tarjetas regalo',
  '5070': 'Ropa de adultos',
  '2412': 'Mascotas',
  '5147': 'Productos ecoamigables',
  '4667': 'Salud',
  '7274': 'Ropa infantil',
  '8710': 'Deportes',
  '4529': 'Productos ecoamigables',
  '4039': 'Dormitorio',
  '3042': 'Celulares'},
 'longitud_nombre_producto': {'8657': 6,
  '5070': 10,
  '2412': 25,
  '5147': 33,
  '4667': 34,
  '7274': 36,
  '8710': 32,
  '4529': 37,
  '4039': 17,
  '3042': 22},
 'longitud_descripcion_producto': {'8657': 34,
  '5070': 39,
  '2412': 12,
  '5147': 25,
  '4667': 22,
  '7274': 28,
  '8710': 17,
  '4529': 3,
  '4039': 39,
  '3042': 35},
 'cantidad_fotos_producto': {'8657': 18,
  '5070': 0,
  '2412': 3,
  '5147': 25,
  '4667': 11,
  '7274': 16,
  '8710': 30,
  '4529': 4,
  '4039': 36,
  '3042': 21},
 'longitud_cm_producto': {'8657': 50,
  '5070': 26,
  '2412': 51,
  '5147': 19,
  '4667': 39,
  '7274': 39,
  '8710': 7,
  '4529': 21,
  '4039': 29,
  '3042': 39},
 'altura_cm_producto': {'8657': 9,
  '5070': 24,
  '2412': 2,
  '5147': 26,
  '4667': 19,
  '7274': 24,
  '8710': 17,
  '4529': 8,
  '4039': 18,
  '3042': 14},
 'ancho_cm_producto': {'8657': 12,
  '5070': 23,
  '2412': 28,
  '5147': 28,
  '4667': 40,
  '7274': 1,
  '8710': 22,
  '4529': 23,
  '4039': 36,
  '3042': 4}}

In [27]:
data_json = pd.DataFrame(data_json)
data_json.head(20)

,producto_id,fecha_envio_limite,nombre_categoria_producto,longitud_nombre_producto,longitud_descripcion_producto,cantidad_fotos_producto,longitud_cm_producto,altura_cm_producto,ancho_cm_producto
8657,PT66,19/09/2017 07:24,Tarjetas regalo,6,34,18,50,9,12
5070,PB76,22/01/2018 11:30,Ropa de adultos,10,39,0,26,24,23
2412,PJ55,09/12/2017 15:09,Mascotas,25,12,3,51,2,28
5147,PO85,04/05/2018 04:15,Productos ecoamigables,33,25,25,19,26,28
4667,PG31,17/09/2017 23:24,Salud,34,22,11,39,19,40
7274,PC48,22/11/2017 01:10,Ropa infantil,36,28,16,39,24,1
8710,PK81,23/02/2018 04:05,Deportes,32,17,30,7,17,22
4529,PO23,14/03/2018 19:45,Productos ecoamigables,37,3,4,21,8,23
4039,PN99,05/03/2018 09:58,Dormitorio,17,39,36,29,18,36
3042,PD94,22/04/2018 02:19,Celulares,22,35,21,39,14,4

In [28]:
data_json.dtypes

producto_id                      object
fecha_envio_limite               object
nombre_categoria_producto        object
longitud_nombre_producto          int64
longitud_descripcion_producto     int64
cantidad_fotos_producto           int64
longitud_cm_producto              int64
altura_cm_producto                int64
ancho_cm_producto                 int64
dtype: object

In [29]:
print(data_json.shape)

(10, 9)

In [30]:
data_json['fecha_envio_limite'] = pd.to_datetime(data_json['fecha_envio_limite'], dayfirst=True)
data_json['fecha_envio_limite']

8657   2017-09-19 07:24:00
5070   2018-01-22 11:30:00
2412   2017-12-09 15:09:00
5147   2018-05-04 04:15:00
4667   2017-09-17 23:24:00
7274   2017-11-22 01:10:00
8710   2018-02-23 04:05:00
4529   2018-03-14 19:45:00
4039   2018-03-05 09:58:00
3042   2018-04-22 02:19:00
Name: fecha_envio_limite, dtype: datetime64[ns]

In [31]:
data_json['day_month'] = data_json['fecha_envio_limite'].dt.strftime('%d-%m')

shopping_per_day_json = data_json['day_month'].value_counts()

print(shopping_per_day_json.head())

day_month
19-09    1
22-01    1
09-12    1
04-05    1
17-09    1
Name: count, dtype: int64

In [32]:
data_json['nombre_categoria_producto'].value_counts()

nombre_categoria_producto
Productos ecoamigables    2
Tarjetas regalo           1
Ropa de adultos           1
Mascotas                  1
Salud                     1
Ropa infantil             1
Deportes                  1
Dormitorio                1
Celulares                 1
Name: count, dtype: int64

# Summary of the Dataset Comparison

### Structure and Size

| Dataset | Rows | Columns | Notes |
|---------|-------|----------|---------------|
| CSV | 1,000 | 9 | Same structure as Excel Sheet 2 |
| Excel - Sheet 1 | 100 | 9 | Unnamed columns (0,1,2,4) |
| Excel - Sheet 2 | 1,000 | 9 | Same structure as CSV |
| JSON | 10 | 10 | Small dataset, same columns |

### The Biggest Shopping Day

| Dataset | Date | Purchases |
|---------|-----|---------|
| CSV | 11/30 | 10 |
| Excel - Sheet 1 | 07/15 | 3 |
| Excel - Sheet 2 | 11/30 | 10 |
| JSON | 09/19 | 1 |

The largest datasets (CSV and Excel Sheet 2) agree on the day with the most purchases: November 30.

### Most Frequent Category

| Dataset | Category | Frequency |
|---------|-----------|------------|
| CSV | Adult Clothing | 70 |
| Excel - Sheet 1 | Toys | 10 |
| Excel - Sheet 2 | Adult Clothing | 70 |
| JSON | Eco-friendly Products | 2 |

Once again, CSV and Excel Sheet 2 agree on the predominant category: Adult Clothing.

### Conclusion

- **CSV and Excel Sheet 2** are equivalent (same dimensions, same patterns)
- **Excel Sheet 1** is a smaller dataset (100 rows) with a different structure
- **JSON** is a minimal dataset (10 rows) for demonstration purposes